In [1]:
import pandas as pd
import numpy as np

In [2]:
dataframes = []

for i in ["0.3", "0.5", "1.0", "1.5", "2.0"]:
    nodes = "modularity/cosmere_gephi_v3_{}.csv".format(i)
    output = "modularity/cosmere_gephi_v3_{}_modularity.csv".format(i)

    nodes_df = pd.read_csv(nodes)

    edges = "cosmere_edges.csv"
    edges_df = pd.read_csv(edges, sep=";")

    total_nodes = len(nodes_df)
    total_edges = len(edges_df)
    print(len(nodes_df), len(edges_df))

    nodes_df = nodes_df[nodes_df["componentnumber"] == 0]
    nodes_filter_ids = nodes_df["Id"].values
    edges_df = edges_df[(edges_df["source"].isin(nodes_filter_ids)) & (edges_df["target"].isin(nodes_filter_ids))]

    print(len(nodes_df), len(edges_df))

    nodes_modularity_clases = nodes_df["modularity_class"]
    nodes_modularity_clases = np.unique(nodes_modularity_clases)

    print(nodes_modularity_clases)

    mod_dict = {}
    for mod_class in nodes_modularity_clases:
        nodes_filter = nodes_df[nodes_df["modularity_class"] == mod_class]
        nodes_filter_ids = nodes_df[nodes_df["modularity_class"] == mod_class]["Id"].values
        edges_filter = edges_df[(edges_df["source"].isin(nodes_filter_ids)) & (edges_df["target"].isin(nodes_filter_ids))]

        mod_dict[mod_class] = {
            "res" : i, 
            "mod_class": mod_class,
            "N nodos": len(nodes_filter),
            "% nodos": len(nodes_filter)/total_nodes,
            "N enlaces": len(edges_filter),
            "% enlaces": len(edges_filter)/total_edges
        }

    dataframe = pd.DataFrame().from_dict(mod_dict).T

    print(dataframe)
    dataframes.append(dataframe)

    dataframe.to_csv(output)

dataframe = pd.concat(dataframes)
dataframe.to_csv("modularity/cosmere_gephi_v3_modularity.csv")

943 31218
909 31140
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
    res mod_class N nodos   % nodos N enlaces % enlaces
1   0.3         1      68   0.07211       918  0.029406
2   0.3         2      97  0.102863      1580  0.050612
3   0.3         3     102  0.108165      5151  0.165001
4   0.3         4       9  0.009544        36  0.001153
5   0.3         5      62  0.065748      1850  0.059261
6   0.3         6      43  0.045599       853  0.027324
7   0.3         7      13  0.013786        78  0.002499
8   0.3         8      69  0.073171      1906  0.061055
9   0.3         9      66  0.069989      1423  0.045583
10  0.3        10      30  0.031813       435  0.013934
11  0.3        11      17  0.018028        51  0.001634
12  0.3        12      26  0.027572       325  0.010411
13  0.3        13      19  0.020148       139  0.004453
14  0.3        14      31  0.032874       321  0.010283
15  0.3        15      79  0.083775      2527  0.080947
16  0.3      

In [3]:
dataframes = []

for i in ["0.3", "0.5", "1.0", "1.5", "2.0"]:
    nodes = "modularity/cosmere_gephi_v3_{}.csv".format(i)
    output = "modularity/cosmere_gephi_v3_{}_modularity.csv".format(i)

    nodes_df = pd.read_csv(nodes)

    edges = "cosmere_edges.csv"
    edges_df = pd.read_csv(edges, sep=";")

    total_nodes = len(nodes_df)
    total_edges = len(edges_df)
    print(len(nodes_df), len(edges_df))

    nodes_df = nodes_df[nodes_df["componentnumber"] == 0]
    nodes_filter_ids = nodes_df["Id"].values
    edges_df = edges_df[(edges_df["source"].isin(nodes_filter_ids)) & (edges_df["target"].isin(nodes_filter_ids))]

    print(len(nodes_df), len(edges_df))

    nodes_modularity_clases = nodes_df["Cluster"]
    nodes_modularity_clases = np.unique(nodes_modularity_clases)

    print(nodes_modularity_clases)

    mod_dict = {}
    for mod_class in nodes_modularity_clases:
        nodes_filter = nodes_df[nodes_df["Cluster"] == mod_class]
        nodes_filter_ids = nodes_df[nodes_df["Cluster"] == mod_class]["Id"].values
        edges_filter = edges_df[(edges_df["source"].isin(nodes_filter_ids)) & (edges_df["target"].isin(nodes_filter_ids))]

        mod_dict[mod_class] = {
            "res" : i, 
            "mod_class": mod_class,
            "N nodos": len(nodes_filter),
            "% nodos": len(nodes_filter)/total_nodes,
            "N enlaces": len(edges_filter),
            "% enlaces": len(edges_filter)/total_edges
        }

    dataframe = pd.DataFrame().from_dict(mod_dict).T

    print(dataframe)
    dataframes.append(dataframe)

    dataframe.to_csv(output)

dataframe = pd.concat(dataframes)
dataframe.to_csv("modularity/cosmere_gephi_v3_cluster.csv")

943 31218
909 31140
[0 1 2 3 4]
   res mod_class N nodos   % nodos N enlaces % enlaces
0  0.3         0     364  0.386002     15043  0.481869
1  0.3         1     192  0.203606      4132   0.13236
2  0.3         2     173  0.183457      6565  0.210295
3  0.3         3     167  0.177094      3304  0.105836
4  0.3         4      13  0.013786        78  0.002499
943 31218
909 31140
[0 1 2 3 4 5 6]
   res mod_class N nodos   % nodos N enlaces % enlaces
0  0.5         0     250  0.265111     10391  0.332853
1  0.5         1     190  0.201485      4010  0.128452
2  0.5         2     170  0.180276      3366  0.107822
3  0.5         3     150  0.159067      6323  0.202543
4  0.5         4     112   0.11877      3158   0.10116
5  0.5         5      24  0.025451       276  0.008841
6  0.5         6      13  0.013786        78  0.002499
943 31218
909 31140
[ 0  1  2  3  4  5  6  7  8  9 11 14]
    res mod_class N nodos   % nodos N enlaces % enlaces
0   1.0         0     190  0.201485      4010  0